services:
  Capo2Keys:
    build:
      context: .
      dockerfile: dockerfile
    image: capo2keys:local
    container_name: capo2keys
    ports:
      - "4506:4506"
    volumes:
      - ./data:/data
    restart: unless-stopped